Repository wecode-bootcamp-korea/15-1st-GITOMP-frontend, pull requests merged in 2020-12, with the labels that each got.

#10 [15기 김규빈] 공통 푸터 코드 리팩토링 완료
  public/images/awd_mark.png
  public/images/sns_blog.png
  public/images/sns_facebook.png
  public/images/sns_insta.png
  public/images/sns_youtb.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/Account/Account.js
  src/Routes.js
  src/styles/common.scss
Labels: Status: Accepted

#9 [15기 김규빈] Add: 앨범 게시판 모든 기능 완료 && 충돌 해결
  package-lock.json
  public/images/favi-bugs.jpg
  public/images/favi-flo.jpg
  public/images/favi-genie.jpg
  public/images/favi-melon.jpg
  public/images/favi-naverm.jpg
  public/images/gitomp_bg.jpg
  src/Pages/AlbumList/AlbumCard.js
  src/Pages/AlbumList/AlbumDetail.js
  src/Pages/AlbumList/AlbumDetail.scss
  src/Pages/AlbumList/AlbumHeadTitle.js
  src/Pages/AlbumList/AlbumHeadTitle.scss
  src/Pages/AlbumList/AlbumList.js
  src/Pages/AlbumList/AlbumList.scss
  src/Pages/AlbumList/List.js
  src/Pages/AlbumList/List.scss
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#8 [15기 박소윤] 코드리뷰 수정, 라우터 기능 오류 수정, 컴플릿 수정완료
  package-lock.json
  package.json
  public/images/album.jpg
  public/images/artist.jpg
  public/images/commuity.jpg
  public/images/consert.jpg
  public/images/logo.gif
  public/images/logo.png
  public/images/logo_bg.jpg
  public/images/search-icon_b.png
  src/Components/Header/Header.js
  src/Components/Header/Nav.js
  src/Components/Header/Nav.scss
  src/Components/Header/SearchBox/SearchBar.js
  src/Components/Header/SearchBox/SearchBar.scss
  src/Components/Header/components/Category.js
  src/Components/Header/components/Category.scss
  src/Components/Header/components/HamMenu.js
  src/Components/Header/components/HamMenu.scss
  src/Components/Header/images/close-icon.png
  src/Components/Header/images/gitomp_bg.jpg
  src/Components/Header/images/hammenu_bg.jpg
  src/Components/Header/images/link-arr.png
  src/Components/Header/images/logo.png
  src/Components/Header/images/search-icon.png
  src/Pages/Commuity/Commuity.js
  src/Pages/Commuity/Commuity.scss
  src/Pages/ConcertList/ConcertList.js
  src/Pages/Notice/Notice.scss
  src/Routes.js
  src/styles/common.scss
Labels: Status: 리뷰 요청, Status: 수정 요청

#2 Header 레이아웃 작업 진행 및 기능 구현 병행 진행중
  public/images/search-icon.png
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Header/components/Category.js
  src/Components/Header/components/Category.scss
  src/Components/Header/components/HamMenu.js
  src/Components/Header/components/HamMenu.scss
  src/Routes.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#14 [15기 박소윤] 머지된 브랜치 소소하게 추가 수정완료
  src/Components/Header/Nav.js
  src/Components/Header/Nav.scss
  src/Components/Header/SearchBox/SearchBar.scss
  src/Components/Header/components/Category.scss
  src/Components/Header/components/HamMenu.scss
  src/Components/Header/components/Nickname.js
  src/Pages/ConcertList/ConcertList.js
Labels: Status: 리뷰 요청
